name: Django-React Fullstack Twitter-Clone

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Construir e iniciar os containers
      - name: Build and start containers
        run: docker compose up -d --build

      # Dar tempo para inicialização
      - name: Wait for containers to initialize
        run: sleep 30

      # Executar migrações usando Poetry
      - name: Run backend migrations
        run: docker compose exec -T web sh -c "poetry run python manage.py migrate"

      # Executar testes do backend usando Poetry
      - name: Run backend tests
        run: docker compose exec -T web sh -c "poetry run python manage.py test"

      # Executar testes do frontend
      - name: Run frontend tests
        run: docker compose exec -T frontend npm test -- --watchAll=false || true

      # Parar os containers
      - name: Stop containers
        run: docker compose down

  build-images:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/django-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/twitter_clone
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/react-frontend:latest
